/* 未尽：离线优先。所有数据与 DeepSeek Key 仅写入当前浏览器 localStorage。 */
const KEY='weijin-state-v1';
const $=s=>document.querySelector(s); const id=()=>crypto.randomUUID();
const defaultState={tasks:[],life:[],projects:[],sessions:[],reports:[],settings:{apiKey:'',capacity:10,weekStart:'2026-08-10'},timer:null};
let state=load(), view='today', draftText='', deferredInstallPrompt=null;
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY))}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateText(){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}
function minutes(t){return Math.round(t/60000)} function hours(n){return (n/60).toFixed(n%60?1:0)+'h'}
function open(html){document.body.insertAdjacentHTML('beforeend',`<div class="sheet-backdrop" onclick="if(event.target===this)this.remove()"><section class="sheet">${html}</section></div>`)}
function close(){document.querySelector('.sheet-backdrop')?.remove()} function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function activeTasks(){return state.tasks.filter(t=>t.status==='committed'||t.status==='candidate'||t.status==='active')}
function usedMinutes(){return state.sessions.reduce((n,s)=>n+(s.endedAt?minutes(new Date(s.endedAt)-new Date(s.startedAt)):0),0)}
function remaining(){return Math.max(0,state.settings.capacity*60-usedMinutes()-activeTasks().filter(t=>t.status!=='active').reduce((n,t)=>n+(+t.estimate||0),0))}
function today(){return state.tasks.filter(t=>['committed','active'].includes(t.status)).sort((a,b)=>(a.priority||9)-(b.priority||9)).slice(0,3)}
function pageToday(){const work=today(), life=state.life.filter(x=>x.status==='planned').slice(0,3), running=state.timer&&state.tasks.find(t=>t.id===state.timer.taskId); return `
 <header class="masthead"><div><div class="brand">未尽</div><div class="brand-subtitle">你的个人 AI 秘书</div></div><button class="leaf-mark" onclick="settings()" aria-label="设置">❧</button></header>
 <div class="date-line">${dateText()}</div><h1>${running?'专注在这一件事上':'今天，先做这一件'}</h1><div class="brush-line"></div>
 <section class="work-panel"><div class="panel-label"><span>▣</span> 工作</div>${running?timerCard(running):work[0]?focusCard(work[0],work.slice(1)):empty('今天还没有工作承诺','把脑中的事告诉秘书，它会帮你归类和安排。')}</section>
 <section class="life-panel"><div class="panel-label"><span>♣</span> 生活</div>${life.map(lifeRow).join('')||'<div class="empty">生活也值得被留出时间。</div>'}</section>`}
 function focusCard(t,next=[]){return `<div class="focus-main"><div class="priority-no">1</div><div class="focus-copy"><div class="task-name">${esc(t.title)}</div><div class="meta">预计剩余 <b>${t.remaining?hours(t.remaining):hours(+t.estimate||0)}</b></div></div></div><button class="primary" onclick="startTimer('${t.id}')">◯&nbsp;&nbsp;开始计时</button>${next.length?`<div class="next-tasks">${next.map((x,i)=>`<button class="next-task" onclick="startTimer('${x.id}')"><span>${i+2}</span><b>${esc(x.title)}</b><i>›</i></button>`).join('')}</div>`:''}`}
 function timerCard(t){return `<section class="focus-card"><div class="eyebrow">正在专注</div><div class="task-name">${esc(t.title)}</div><div class="timer" id="timer-text">00:00:00</div><div class="row"><button class="secondary" onclick="pauseTimer()">暂停</button><button class="primary" style="margin:0" onclick="finishTask('${t.id}')">结束</button></div></section>`}
 function taskRow(t){return `<div class="item"><button class="round ${t.status==='done'?'done':''}" onclick="finishTask('${t.id}')">${t.status==='done'?'✓':'○'}</button><div class="item-main"><div class="item-title">${esc(t.title)}</div><div class="meta">${esc(t.project||'未归属项目')} · ${t.remaining?`还剩 ${hours(t.remaining)}`:`预计 ${hours(+t.estimate||0)}`}</div></div><div class="item-actions"><button class="round" onclick="startTimer('${t.id}')">▷</button><button class="round" onclick="taskMenu('${t.id}')">⋮</button></div></div>`}
 function lifeRow(x){return `<div class="life-item"><div class="life-icon">${x.kind==='relation'?'☎':'⌂'}</div><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="meta">${x.when||'本周找合适时间'} · 约 ${hours(+x.estimate||0)}</div></div><button class="life-arrow" onclick="lifeDone('${x.id}')">›</button></div>`}
 function empty(a,b){return `<div class="empty"><b>${a}</b><br><small>${b}</small></div>`}
 function pageWeek(){const tasks=activeTasks(), life=state.life.filter(x=>x.status==='planned');return `<header class="topbar"><div><div class="brand">本周</div><div class="date">先看真实容量，再做承诺</div></div><button class="icon-btn" onclick="planWeek()">＋</button></header><section class="focus-card"><div class="eyebrow">本周可靠容量</div><div class="task-name">还可以承诺 ${hours(remaining())}</div><div class="meta">已记录 ${hours(usedMinutes())} · 设置容量 ${state.settings.capacity}h</div><button class="primary" onclick="planWeek()">和秘书做周计划</button></section><div class="section-title">工作承诺 <span>${tasks.length} 项</span></div><div class="list">${tasks.map(taskRow).join('')||'<div class="empty">还没有本周承诺。</div>'}</div><div class="section-title">生活安排 <span>${life.length} 项</span></div><div class="list">${life.map(lifeRow).join('')||'<div class="empty">生活也可以被留出空间。</div>'}</div>`}
 function pageReports(){const r=buildReport(false);return `<header class="topbar"><div><div class="brand">周报</div><div class="date">事实、原因、下一步</div></div><button class="icon-btn" onclick="exportMenu()">⇩</button></header><div class="kpis"><div class="kpi"><b>${r.done}/${r.total}</b><span>本周工作完成</span></div><div class="kpi"><b>${hours(r.actual)}</b><span>实际专注投入</span></div><div class="kpi"><b>${r.bias}</b><span>平均估时偏差</span></div><div class="kpi"><b>${hours(remaining())}</b><span>剩余可靠容量</span></div></div><section class="report-card"><h3>本周承诺</h3>${r.lines||'<p>先录入本周要做的事。</p>'}</section><section class="report-card"><h3>秘书的判断</h3><p>${r.advice}</p></section><section class="report-card"><h3>下周建议</h3><ul><li>延续仍有价值的未完成项，不自动背债。</li><li>按本周实际数据，再确认下周承诺。</li><li>周六保持完整休息，不排工作承诺。</li></ul></section><button class="primary" onclick="saveReport()">保存本周周报</button>`}
 function pageSettings(){return `<header class="topbar"><div><div class="brand">设置</div><div class="date">数据只保留在这台设备</div></div></header><section class="setting-card" style="padding:16px"><div class="eyebrow">安装应用</div><p>安装后会以独立应用打开，不显示浏览器地址栏。</p><button class="primary" onclick="installApp()">安装未尽</button></section><section class="setting-card" style="padding:16px;margin-top:12px"><div class="eyebrow">DeepSeek</div><p>密钥不会写进 GitHub，只保存于浏览器。</p><div class="field"><label>API Key</label><input id="api-key" type="password" placeholder="sk-..." value="${esc(state.settings.apiKey)}"></div><button class="primary" onclick="saveSettings()">保存设置</button></section><section class="setting-card" style="padding:16px;margin-top:12px"><div class="eyebrow">本周容量</div><div class="field"><label>本周可承诺专注时长（小时）</label><input id="capacity" type="number" min="1" max="100" value="${state.settings.capacity}"></div><button class="secondary" onclick="saveSettings()">更新容量</button></section><section class="setting-card" style="padding:16px;margin-top:12px"><div class="eyebrow">数据</div><p>可导出完整备份，换手机前请先保存 JSON 文件。</p><button class="secondary" onclick="exportMenu()">导出与备份</button></section>`}
 function render(){const pages={today:pageToday,week:pageWeek,reports:pageReports,settings:pageSettings};$('#app').innerHTML=`${pages[view]()}${view==='settings'?'':dock()}${view==='settings'?'<div class="nav"><button onclick="go(\'today\')"><b>⌂</b>今天</button><button onclick="go(\'week\')"><b>□</b>本周</button><button onclick="go(\'reports\')"><b>▤</b>周报</button><button class="active"><b>⚙</b>设置</button></div>':nav()}`;if(state.timer)tick()}
 function dock(){return `<form class="input-dock" onsubmit="capture(event)"><input id="capture" autocomplete="off" placeholder="随时告诉秘书一件事…" value="${esc(draftText)}"><button class="send" aria-label="发送">↑</button></form>`}
 function nav(){return `<nav class="nav"><button class="${view==='today'?'active':''}" onclick="go('today')"><b>⌂</b>今天</button><button class="${view==='week'?'active':''}" onclick="go('week')"><b>□</b>本周</button><button class="${view==='reports'?'active':''}" onclick="go('reports')"><b>◴</b>周报</button><button onclick="go('settings')"><b>⚙</b>设置</button></nav>`}
 function go(v){view=v;render()} function settings(){go('settings')}
 function capture(e){e.preventDefault();const input=$('#capture');draftText=input.value.trim();if(!draftText)return;parseInput(draftText)}
 async function parseInput(text){open(`<h2>秘书正在整理</h2><p>我会先理解你说的任务、生活安排和时间意图。</p><div class="notice">${esc(text)}</div>`);let items=[];try{items=state.settings.apiKey?await aiParse(text):heuristic(text)}catch{items=heuristic(text);toast('AI 暂不可用，已用本地规则整理')}showDraft(items,text)}
 function heuristic(text){const life=/姐姐|朋友|老公|家里|被单|被套|大扫除|家庭财务|吃饭|聊天/.test(text);const status=/下周|以后|暂缓|先录入/.test(text)?'later':/候选|最好|想做/.test(text)?'candidate':'committed';const clean=text.replace(/这周|需要|完成|安排|先录入|下周|估计没办法|，/g,' ').trim();return clean.split(/[、；;\n]|和/).filter(s=>s.trim().length>1).map(s=>({title:s.trim(),type:life?'life':'work',status,project:'',estimate:life?30:60,reason:status==='later'?'已识别为以后再说':'建议本周处理'}))}
 async function aiParse(text){const prompt=`你是中文个人秘书。根据用户输入抽取工作或生活安排。返回纯 JSON 数组，不要 markdown。字段：title,type(work|life),status(committed|candidate|later|blocked),project,estimate(分钟整数),kind(relation|home|other),reason。用户输入：${text}`;const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.apiKey},body:JSON.stringify({model:'deepseek-chat',temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:'只输出 {"items":[...]}。估时无法判断时工作60分钟、生活30分钟。'},{role:'user',content:prompt}]})});if(!r.ok)throw Error('API');const data=await r.json();return JSON.parse(data.choices[0].message.content).items}
 function showDraft(items,text){const body=items.map((x,i)=>`<div class="task-draft"><div class="draft-title">${esc(x.title)}</div><div class="draft-meta">${x.type==='life'?'生活安排':'工作'} · ${label(x.status)} · ${x.project?esc(x.project)+' · ':''}预估 <input id="est-${i}" type="number" min="5" value="${x.estimate||60}" style="width:62px;padding:3px;border:1px solid var(--line);border-radius:6px"> 分钟</div></div>`).join('');close();open(`<h2>这样理解对吗？</h2><p>你的原话优先。我只在容量或依赖冲突时提出建议。</p>${body}<button class="primary" onclick='confirmDraft(${JSON.stringify(items).replace(/'/g,"&#39;")})'>确认录入</button><button class="text-btn" onclick="close()">返回修改</button>`)}
 function label(s){return ({committed:'本周承诺',candidate:'本周候选',later:'以后再说',blocked:'受阻'}[s]||s)}
 function confirmDraft(items){items.forEach((x,i)=>{x.estimate=+document.querySelector('#est-'+i).value||60;if(x.type==='life')state.life.push({id:id(),title:x.title,kind:x.kind||'home',estimate:x.estimate,status:'planned',when:'本周找合适时间'});else state.tasks.push({id:id(),title:x.title,project:x.project||'',estimate:x.estimate,remaining:0,status:x.status,priority:x.status==='committed'?1:5,createdAt:new Date().toISOString()})});close();const over=remaining()<0;save();toast(over?'已录入，但本周超容量，请到本周页决定取舍。':'已录入。秘书会按你的承诺安排。')}
 function startTimer(taskId){if(state.timer&&state.timer.taskId!==taskId){toast('请先暂停正在计时的任务');return}if(!state.timer){state.timer={taskId,startedAt:new Date().toISOString()};const t=state.tasks.find(x=>x.id===taskId);t.status='active';save()} }
 function pauseTimer(){if(!state.timer)return;state.sessions.push({id:id(),taskId:state.timer.taskId,startedAt:state.timer.startedAt,endedAt:new Date().toISOString()});const t=state.tasks.find(x=>x.id===state.timer.taskId);if(t)t.status='committed';state.timer=null;save();toast('已暂停，真实投入已记录')}
 function finishTask(taskId){if(state.timer?.taskId===taskId)pauseTimer();const t=state.tasks.find(x=>x.id===taskId);if(!t)return;open(`<h2>这件事完成了吗？</h2><p>未完成也不是失败。告诉秘书还需多久，它会按真实剩余工作量重排。</p><div class="notice">${esc(t.title)}</div><div class="row"><button class="secondary" onclick="markRemaining('${taskId}')">还没完成</button><button class="primary" style="margin:0" onclick="markDone('${taskId}')">已完成</button></div>`)}
 function markDone(taskId){const t=state.tasks.find(x=>x.id===taskId);t.status='done';t.completedAt=new Date().toISOString();close();save();toast('完成已记录。今天不用自动加新任务。')}
 function markRemaining(taskId){const t=state.tasks.find(x=>x.id===taskId);close();open(`<h2>还需要多久？</h2><p>这是校准预估，不是自我批评。</p><div class="field"><label>预计剩余分钟</label><input id="remain" type="number" min="5" value="${t.remaining||t.estimate||60}"></div><button class="primary" onclick="saveRemaining('${taskId}')">保存并重排</button>`)}
 function saveRemaining(taskId){const t=state.tasks.find(x=>x.id===taskId);t.remaining=+$('#remain').value||0;t.status='committed';close();save();toast(remaining()<0?'剩余工作已更新。本周已超容量，请重排。':'剩余工作已纳入本周。')}
 function lifeDone(i){const x=state.life.find(x=>x.id===i);x.status='done';save();toast('已记录。生活不是 KPI。')}
 function taskMenu(i){const t=state.tasks.find(x=>x.id===i);open(`<h2>${esc(t.title)}</h2><p>${t.project?`项目：${esc(t.project)}`:'尚未归属项目'}</p><button class="secondary" onclick="blockTask('${i}')">标记受阻</button><button class="secondary danger" onclick="removeTask('${i}')">删除此项</button>`)}
 function blockTask(i){const t=state.tasks.find(x=>x.id===i);t.status='blocked';close();save();toast('已标记受阻，不再占用今日目标。')}
 function removeTask(i){state.tasks=state.tasks.filter(x=>x.id!==i);close();save();toast('已移除')}
 function planWeek(){const r=remaining();open(`<h2>本周容量检查</h2><p>秘书不会默默把新事塞进你的一周。</p><div class="notice ${r<0?'warn':''}">${r>=0?`还可承诺 ${hours(r)}。`: `本周已超容量 ${hours(-r)}。需要顺延、降级，或明确开启例外冲刺。`}</div><p>周日 20:00-23:30 是默认规划窗口。周六不安排工作承诺。</p><button class="primary" onclick="close()">我知道了</button>`)}
 function buildReport(){const ts=state.tasks.filter(t=>t.status!=='later'),done=ts.filter(t=>t.status==='done'), estimates=done.reduce((n,t)=>n+(+t.estimate||0),0),actual=state.sessions.reduce((n,s)=>n+(s.endedAt?minutes(new Date(s.endedAt)-new Date(s.startedAt)):0),0),bias=estimates?`${Math.round((actual-estimates)/estimates*100)}%`:'暂无';return {total:ts.length,done:done.length,actual,bias,lines:ts.map(t=>`<div class="item-title">${t.status==='done'?'✓':t.status==='blocked'?'⊘':'◐'} ${esc(t.title)}</div><div class="meta">${label(t.status)} · 预计 ${hours(+t.estimate||0)}${t.remaining?' · 还剩 '+hours(t.remaining):''}</div>`).join('<br>'),advice:ts.length===0?'先把下一周真正想完成的事录入。':remaining()<0?'这周的承诺已经超过可靠容量。先顺延代价最小的一项，而不是依赖熬夜偿还。':done.length<ts.length?'未完成并不说明投入不足。先检查估时、受阻和可用容量，再决定下周是否延续。':'你兑现了本周承诺。下周可以小幅增加挑战，但仍保留缓冲。'}}
 function saveReport(){const r=buildReport();state.reports.unshift({id:id(),createdAt:new Date().toISOString(),...r});save();toast('周报已保存到本机')}
 function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
 function exportMenu(){open(`<h2>导出与备份</h2><p>导出后可换手机恢复。请妥善保管，JSON 包含本地设置。</p><button class="primary" onclick="download('未尽-完整备份.json','application/json',JSON.stringify(state,null,2));close()">导出完整 JSON</button><button class="secondary" style="margin-top:9px" onclick="exportMd()">导出本周周报 Markdown</button><button class="secondary" style="margin-top:9px" onclick="exportCsv()">导出任务 CSV</button>`)}
 function exportMd(){const r=buildReport();const md=`# 未尽 · 本周周报\n\n- 完成：${r.done}/${r.total}\n- 实际专注：${hours(r.actual)}\n- 估时偏差：${r.bias}\n\n## 秘书的判断\n${r.advice.replace(/<[^>]+>/g,'')}\n`;download('未尽-本周周报.md','text/markdown;charset=utf-8',md);close()}
 function exportCsv(){const rows=['任务,项目,状态,预计分钟,剩余分钟',...state.tasks.map(t=>[t.title,t.project,label(t.status),t.estimate,t.remaining||''].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(','))];download('未尽-任务.csv','text/csv;charset=utf-8','\ufeff'+rows.join('\n'));close()}
 function saveSettings(){state.settings.apiKey=$('#api-key').value.trim();state.settings.capacity=+$('#capacity').value||10;save();toast('设置已保存在本机')}
 function tick(){const el=$('#timer-text');if(!el||!state.timer)return;const d=Date.now()-new Date(state.timer.startedAt);const h=String(Math.floor(d/3600000)).padStart(2,'0'),m=String(Math.floor(d/60000)%60).padStart(2,'0'),s=String(Math.floor(d/1000)%60).padStart(2,'0');el.textContent=`${h}:${m}:${s}`;setTimeout(tick,500)}
 async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();const result=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;toast(result.outcome==='accepted'?'正在安装未尽':'已取消安装');return}open(`<h2>安装未尽</h2><p>请用 Chrome 打开本页，点击右上角菜单，选择“安装应用”或“安装未尽”。华为浏览器的“保存到桌面”通常只是网页快捷方式，仍会显示地址栏。</p><button class="primary" onclick="close()">我知道了</button>`)}
 window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;render()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;toast('未尽已安装到桌面')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=3');render();
