/* 未尽：离线优先 PWA。数据与 DeepSeek Key 仅写入 localStorage。*/
const KEY='weijin-state-v1';
const $=s=>document.querySelector(s); const id=()=>crypto.randomUUID();
const defaultState={tasks:[],life:[],projects:[],sessions:[],reports:[],specialWeeks:[],settings:{apiKey:'',capacity:10},timer:null,reportDrafts:{}};
let state=load(), view='today', draftText='', deferredInstallPrompt=null;
let _swipeState=null, _timerRAF=null;

/* ── 数据 ── */
function isoDate(value){var d=value?new Date(value):new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function weekStartOf(value){var d=value?new Date(value):new Date(),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1);return isoDate(d)}
function addDays(date,days){var d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return isoDate(d)}
function currentWeekStart(){return weekStartOf(new Date())}
function nextWeekStart(){return addDays(currentWeekStart(),7)}
function load(){try{var parsed=JSON.parse(localStorage.getItem(KEY))||{},merged={...structuredClone(defaultState),...parsed,settings:{...defaultState.settings,...(parsed.settings||{})}};merged.tasks=(merged.tasks||[]).map(function(t){var status=t.status==='candidate'?'committed':t.status;return {...t,status:status,weekStart:t.weekStart||(status==='later'?nextWeekStart():currentWeekStart()),plannedDate:t.plannedDate||(status==='later'?nextWeekStart():isoDate()),dependsOn:Array.isArray(t.dependsOn)?t.dependsOn:[]}});merged.life=(merged.life||[]).map(function(x){return {...x,weekStart:x.weekStart||currentWeekStart(),plannedDate:x.plannedDate||isoDate()}});merged.sessions=(merged.sessions||[]).map(function(s){return {...s,durationMs:s.durationMs??(s.endedAt?Math.max(0,new Date(s.endedAt)-new Date(s.startedAt)):0),weekStart:s.weekStart||weekStartOf(s.startedAt)}});if(merged.timer)merged.timer={...merged.timer,paused:merged.timer.paused??!merged.timer.startedAt};return merged}catch{return structuredClone(defaultState)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
function save(){persist();render()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateText(){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}
function minutes(t){return Math.round(t/60000)} function hours(n){var v=Math.max(0,+n||0);return (v/60).toFixed(v%60?1:0)+'h'}
function durationText(ms){var sec=Math.max(0,Math.floor((+ms||0)/1000));if(sec<60)return sec+'秒';var min=Math.floor(sec/60);if(min<60)return min+'分钟';var h=Math.floor(min/60),rest=min%60;return h+'小时'+(rest?rest+'分钟':'')}

/* ── Toast（底部导航上方） ── */
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(el._tid);el._tid=setTimeout(()=>el.classList.remove('show'),2400)}

/* ── Sheet 弹窗 ── */
function open(html){document.body.insertAdjacentHTML('beforeend','<div class="sheet-backdrop" onclick="if(event.target===this)this.remove()"><section class="sheet">'+html+'</section></div>')}
function close(){document.querySelector('.sheet-backdrop')?.remove()}

/* ── 状态计算 ── */
function inCurrentWeek(x){return (x.weekStart||currentWeekStart())===currentWeekStart()}
function activeTasks(){return state.tasks.filter(t=>inCurrentWeek(t)&&['committed','active','paused','blocked'].includes(t.status))}
function taskActualMs(taskId){var saved=state.sessions.filter(s=>s.taskId===taskId).reduce((n,s)=>n+(+s.durationMs||0),0);if(state.timer&&state.timer.taskId===taskId&&!state.timer.paused&&state.timer.startedAt)saved+=Math.max(0,Date.now()-new Date(state.timer.startedAt));return saved}
function usedMs(){return state.sessions.filter(inCurrentWeek).reduce((n,s)=>n+(+s.durationMs||0),0)+(state.timer&&!state.timer.paused&&weekStartOf(state.timer.startedAt)===currentWeekStart()?Math.max(0,Date.now()-new Date(state.timer.startedAt)):0)}
function usedMinutes(){return usedMs()/60000}
function taskPendingMinutes(t){if(t.status==='done')return 0;if(+t.remaining>0)return +t.remaining;return Math.max(0,(+t.estimate||0)-taskActualMs(t.id)/60000)}
function committedForecastMinutes(){return usedMinutes()+activeTasks().reduce((n,t)=>n+taskPendingMinutes(t),0)}
function usedPct(){var cap=state.settings.capacity*60;return cap?Math.min(1,usedMinutes()/cap):0}
function remaining(){return state.settings.capacity*60-committedForecastMinutes()}
function dependencyReady(t){return (t.dependsOn||[]).every(function(depId){var dep=state.tasks.find(function(x){return x.id===depId});return dep&&dep.status==='done'})}
function today(){var now=isoDate();return state.tasks.filter(function(t){return inCurrentWeek(t)&&['committed','active','paused'].includes(t.status)&&(!t.plannedDate||t.plannedDate<=now)&&dependencyReady(t)}).sort(function(a,b){return String(a.plannedDate||'').localeCompare(String(b.plannedDate||''))||(a.priority||9)-(b.priority||9)}).slice(0,3)}

/* ── 环形进度 SVG ── */
function ringSvg(pct,size,sw,cls){var r=(size-sw)/2,c=2*Math.PI*r,o=c*(1-pct);return '<svg viewBox="0 0 '+size+' '+size+'"><circle class="ring-bg" cx="'+(size/2)+'" cy="'+(size/2)+'" r="'+r+'" stroke-width="'+sw+'"/><circle class="'+cls+'" cx="'+(size/2)+'" cy="'+(size/2)+'" r="'+r+'" stroke-width="'+sw+'" stroke-dasharray="'+c+'" stroke-dashoffset="'+o+'"/></svg>'}

/* ── 空状态 ── */
function empty(icon,title,hint){return '<div class="empty-state"><div class="empty-icon">'+icon+'</div><div class="empty-label">'+title+'</div><div class="empty-hint">'+hint+'</div></div>'}

/* ════════════════════════════════════════════
   今日页
   ════════════════════════════════════════════ */
function pageToday(){var work=today(), life=state.life.filter(function(x){return inCurrentWeek(x)&&x.status==='planned'&&(!x.plannedDate||x.plannedDate<=isoDate())}).slice(0,3), running=state.timer&&state.tasks.find(function(t){return t.id===state.timer.taskId}), subtitle=running?(state.timer.paused?'这件事已暂停':'专注在这一件事上'):'今天，先做这一件'; return '\n <header class="masthead"><div><div class="brand">未尽</div><div class="brand-subtitle">你的个人 AI 秘书</div></div><button class="leaf-mark" onclick="settings()" aria-label="设置">⚙️</button></header>\n <div class="date-line">'+dateText()+' · '+subtitle+'</div>\n\n <section class="panel">\n  <div class="panel-label"><span class="emoji">📋</span> 工作</div>\n  '+(running?timerInlineHtml(running):work[0]?focusCardHtml(work[0],work.slice(1)):empty('📝','今天还没有可执行的工作','未来事项或依赖未满足的工作不会被提前塞进今天。'))+'\n </section>\n\n <section class="panel">\n  <div class="panel-label"><span class="emoji">🌿</span> 生活</div>\n  '+(life.length?life.map(lifeRowHtml).join(''):empty('🌸','生活也值得被留出时间','输入「和朋友吃饭」「大扫除」试试。'))+'\n </section>'}
function focusCardHtml(t,next){var actual=taskActualMs(t.id),time=actual>0?'已投入 '+durationText(actual)+' · 预计剩余约 '+hours(taskPendingMinutes(t)):'预计 '+hours(+t.estimate||0); return '\n <div class="focus-main"><div class="priority-badge">1</div><div class="focus-copy"><div class="task-name">'+esc(t.title)+'</div><div class="meta">'+time+'</div></div></div>\n <button class="btn-primary" style="margin-top:12px" onclick="startTimer(\''+t.id+'\')">▶&nbsp;&nbsp;'+(t.status==='paused'?'继续计时':'开始计时')+'</button>\n '+(next.length?'<div class="next-tasks">'+next.map(function(x,i){return '\n  <button class="next-task" onclick="startTimer(\''+x.id+'\')"><span class="seq">'+(i+2)+'</span><span class="title">'+esc(x.title)+'</span><span class="arrow">›</span></button>'}).join('')+'</div>':'')}
function timerInlineHtml(t){return '\n <div style="text-align:center;padding:4px 0">\n  <div class="meta" style="margin-bottom:4px">'+(state.timer.paused?'已暂停':'正在专注')+'</div>\n  <div style="font-family:var(--serif);font-size:18px;font-weight:700;margin-bottom:10px">'+esc(t.title)+'</div>\n  <div id="timer-text" style="font-family:var(--serif);font-size:30px;font-weight:700;letter-spacing:.03em;margin-bottom:12px">'+timerClock(taskActualMs(t.id))+'</div>\n  <button class="btn-primary" onclick="openTimerOverlay(\''+t.id+'\')">打开专注面板</button>\n </div>'}
function lifeRowHtml(x){return '\n <div class="life-item"><div class="life-icon">'+(x.kind==='relation'?'💬':'🏠')+'</div><div class="item-main"><div class="item-title">'+esc(x.title)+'</div><div class="meta">'+(x.when||'本周找合适时间')+' · 约 '+hours(+x.estimate||0)+'</div></div><button class="life-arrow" onclick="lifeDone(\''+x.id+'\')">›</button></div>'}

/* ════════════════════════════════════════════
   本周页
   ════════════════════════════════════════════ */
function pageWeek(){var tasks=activeTasks(), life=state.life.filter(function(x){return inCurrentWeek(x)&&x.status==='planned'}), capPct=usedPct(), rem=remaining(); return '\n <header class="topbar"><div><div class="brand">本周</div><div class="subtitle">先看真实容量，再做承诺</div></div><button class="btn-icon" onclick="planWeek()">＋</button></header>\n\n <div class="capacity-card">\n  <div class="capacity-ring">'+ringSvg(Math.min(1,capPct),80,8,'ring-fill')+'<div class="ring-center">'+Math.round(capPct*100)+'%</div></div>\n  <div class="capacity-info"><div class="main-text">'+(rem>=0?'还可以承诺 '+hours(rem):'已超出可靠容量 '+hours(-rem))+'</div><div class="sub-text">已投入 '+hours(usedMinutes())+' · 可靠容量 '+state.settings.capacity+'h</div></div>\n </div>\n <button class="btn-primary" style="margin-top:14px" onclick="planWeek()">和秘书做周计划</button>\n\n <div class="section-title">工作承诺 <span class="count">'+tasks.length+' 项</span></div>\n <div class="task-list">'+(tasks.length?tasks.map(taskRowHtml).join(''):empty('📋','还没有本周承诺','在输入框告诉秘书你想做的事。'))+'</div>\n\n <div class="section-title">生活安排 <span class="count">'+life.length+' 项 · 不计工作容量</span></div>\n <div class="task-list">'+(life.length?life.map(lifeRowHtml).join(''):empty('🌸','生活也可以被留出空间','输入你的生活安排，秘书会帮你记住。'))+'</div>'}
function taskRowHtml(t){var actual=taskActualMs(t.id),rem=actual>0?'已投入 '+durationText(actual)+' · 剩余约 '+hours(taskPendingMinutes(t)):'预计 '+hours(+t.estimate||0),deps=(t.dependsOn||[]).map(function(depId){var dep=state.tasks.find(function(x){return x.id===depId});return dep&&dep.title}).filter(Boolean),blocked=t.status==='blocked'||(deps.length&&!dependencyReady(t)),blockText=t.blockedReason||(deps.length?'等待 '+deps.join('、'):'当前受阻'); return '\n <div class="task-row-wrap" data-task-id="'+t.id+'">\n  <div class="swipe-bg"><div class="swipe-action swipe-done" onclick="event.stopPropagation();finishTask(\''+t.id+'\')" data-action="done">✓</div><div class="swipe-action swipe-block" onclick="event.stopPropagation();blockTask(\''+t.id+'\')" data-action="block">⊘</div></div>\n  <div class="task-item" id="task-item-'+t.id+'">\n   <button class="btn-done" onclick="event.stopPropagation();finishTask(\''+t.id+'\')">○</button>\n   <div class="item-main"><div class="item-title">'+esc(t.title)+'</div><div class="meta">'+esc(t.project||'未归属项目')+' · '+(t.plannedDate?esc(t.plannedDate)+' · ':'')+rem+(blocked?' · '+esc(blockText):'')+'</div></div>\n   <div class="item-actions">'+(!blocked?'<button class="btn-sm" onclick="event.stopPropagation();startTimer(\''+t.id+'\')">▶</button>':'')+'<button class="btn-sm" onclick="event.stopPropagation();taskMenu(\''+t.id+'\')">⋮</button></div>\n  </div>\n </div>'}

/* ════════════════════════════════════════════
   周报页
   ════════════════════════════════════════════ */
function pageReports(){var r=buildReport(),draft=state.reportDrafts?.[currentWeekStart()]; return '\n <header class="topbar"><div><div class="brand">周报</div><div class="subtitle">事实、原因、下一步</div></div><button class="btn-icon" onclick="exportMenu()">⇩</button></header>\n\n <div class="kpis">\n  <div class="kpi"><span class="kpi-num">'+r.done+'/'+r.total+'</span><span class="kpi-label">本周工作完成</span></div>\n  <div class="kpi"><span class="kpi-num">'+hours(r.actualMinutes)+'</span><span class="kpi-label">实际专注投入</span></div>\n  <div class="kpi"><span class="kpi-num">'+r.bias+'</span><span class="kpi-label">已完成项估时偏差</span></div>\n  <div class="kpi"><span class="kpi-num">'+(remaining()>=0?hours(remaining()):'-'+hours(-remaining()))+'</span><span class="kpi-label">剩余可靠容量</span></div>\n </div>\n\n <section class="report-card"><h3>工作承诺</h3><ul class="report-list">'+(r.workLines||'<li>本周还没有工作承诺。</li>')+'</ul></section>\n <section class="report-card"><h3>生活安排 <small style="color:var(--muted);font-weight:400">不计工作容量</small></h3><ul class="report-list">'+(r.lifeLines||'<li>本周还没有生活安排。</li>')+'</ul></section>\n <section class="report-card"><h3>秘书的判断</h3><div class="report-advice"><p>'+(draft?esc(draft.judgment):'尚未生成。本区不会使用固定文案冒充 AI 判断。')+'</p></div>'+(draft?'<small class="meta">'+esc(draft.sourceLabel)+'</small>':'<button class="btn-secondary" onclick="generateWeeklyReport()">生成本周判断</button>')+'</section>\n <section class="report-card"><h3>下周建议</h3><ul class="report-suggest">'+(draft&&draft.suggestions?.length?draft.suggestions.map(function(x){return '<li>'+esc(x)+'</li>'}).join(''):'<li>生成本周判断后给出针对性建议。</li>')+'</ul></section>\n\n <button class="btn-primary" onclick="saveReport()">保存本周周报快照</button>'}
function buildReport(){var ws=currentWeekStart(),ts=state.tasks.filter(function(t){return t.weekStart===ws&&t.status!=='later'}),life=state.life.filter(function(x){return x.weekStart===ws}),done=ts.filter(function(t){return t.status==='done'}),estimates=done.reduce(function(n,t){return n+(+t.estimate||0)},0),actualMs=state.sessions.filter(function(s){return s.weekStart===ws}).reduce(function(n,s){return n+(+s.durationMs||0)},0),doneActual=done.reduce(function(n,t){return n+taskActualMs(t.id)/60000},0),bias=estimates?String(Math.round((doneActual-estimates)/estimates*100))+'%':'暂无';return {weekStart:ws,total:ts.length,done:done.length,actualMs:actualMs,actualMinutes:actualMs/60000,bias:bias,tasks:ts,life:life,workLines:ts.map(function(t){return '<li class="'+(t.status==='done'?'done':'')+'">'+esc(t.title)+'<br><small style="color:var(--muted)">'+label(t.status)+' · 预计 '+hours(+t.estimate||0)+' · 实际 '+durationText(taskActualMs(t.id))+(t.plannedDate?' · '+esc(t.plannedDate):'')+'</small></li>'}).join(''),lifeLines:life.map(function(x){return '<li class="'+(x.status==='done'?'done':'')+'">'+esc(x.title)+'<br><small style="color:var(--muted)">'+(x.status==='done'?'已完成':'本周安排')+' · 不计工作容量</small></li>'}).join('')}}
function localReport(r){var blocked=r.tasks.filter(function(t){return t.status==='blocked'}),unfinished=r.total-r.done,judgment=r.total===0?'本周还没有足够的工作数据可供判断。':'本周完成 '+r.done+'/'+r.total+' 项工作，实际专注 '+durationText(r.actualMs)+'。'+(blocked.length?'受阻事项是：'+blocked.map(function(t){return t.title}).join('、')+'。':'')+(remaining()<0?'当前承诺超过可靠容量，不建议继续加塞。':unfinished?'还有 '+unfinished+' 项未完成，先核对依赖和剩余估时。':'本周承诺已兑现。');return {judgment:judgment,suggestions:[blocked.length?'下周先解除受阻依赖，再安排后续事项。':'下周继续按依赖顺序确认 1–3 件每日重点。',r.bias==='暂无'?'继续积累预估与实际时间数据。':'参考本周 '+r.bias+' 的估时偏差调整下周预估。','周六保持完整休息，不排工作承诺。'],sourceLabel:'本地规则摘要 · 非 AI'}}
async function generateWeeklyReport(){var r=buildReport();open('<h2>正在生成周报判断</h2><p>秘书会依据本周真实工作、生活与计时数据给出判断。</p>');var result;try{if(!state.settings.apiKey)throw Error('NO_KEY');var payload={weekStart:r.weekStart,capacityHours:state.settings.capacity,exceptionSprint:state.specialWeeks.includes(r.weekStart),work:r.tasks.map(function(t){return {title:t.title,status:label(t.status),estimateMinutes:t.estimate,actualMinutes:Math.round(taskActualMs(t.id)/60000),remainingMinutes:taskPendingMinutes(t),plannedDate:t.plannedDate,dependencies:(t.dependsOn||[]).map(function(depId){return state.tasks.find(function(x){return x.id===depId})?.title}).filter(Boolean)}}),life:r.life.map(function(x){return {title:x.title,status:x.status,kind:x.kind}})};var response=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.apiKey},body:JSON.stringify({model:'deepseek-chat',temperature:.3,response_format:{type:'json_object'},messages:[{role:'system',content:'你是直接、不哄人的个人秘书。只输出 JSON：{"judgment":"基于事实的判断","suggestions":["最多3条具体建议"]}。生活不计工作KPI；例外冲刺不得作为未来容量标准。'},{role:'user',content:JSON.stringify(payload)}]})});if(!response.ok)throw Error('API');var data=await response.json();result=JSON.parse(data.choices[0].message.content);result.sourceLabel='DeepSeek · 基于本周真实数据'}catch(error){result=localReport(r)}state.reportDrafts=state.reportDrafts||{};state.reportDrafts[r.weekStart]={...result,generatedAt:new Date().toISOString()};close();save();toast(result.sourceLabel.indexOf('DeepSeek')===0?'AI 周报判断已生成':'AI 暂不可用，已生成本地规则摘要')}
function saveReport(){var r=buildReport(),draft=state.reportDrafts?.[r.weekStart]||localReport(r),snapshot={id:id(),weekStart:r.weekStart,createdAt:new Date().toISOString(),done:r.done,total:r.total,actualMinutes:r.actualMinutes,bias:r.bias,work:r.tasks.map(function(t){return {...t,actualMs:taskActualMs(t.id)}}),life:r.life.map(function(x){return {...x}}),judgment:draft.judgment,suggestions:draft.suggestions,sourceLabel:draft.sourceLabel};state.reports=state.reports.filter(function(x){return x.weekStart!==r.weekStart});state.reports.unshift(snapshot);save();toast('本周周报快照已保存')}

/* ════════════════════════════════════════════
   设置页
   ════════════════════════════════════════════ */
function pageSettings(){return '\n <header class="topbar"><div><div class="brand">设置</div><div class="subtitle">数据只保留在这台设备</div></div></header>\n\n <section class="setting-card"><div class="eyebrow">DeepSeek AI</div><p>密钥不会写进 GitHub，只保存于浏览器。</p><div class="field"><label>API Key</label><input id="api-key" type="password" placeholder="sk-..." value="'+esc(state.settings.apiKey)+'"></div><button class="btn-primary" onclick="saveSettings()">保存设置</button></section>\n\n <section class="setting-card"><div class="eyebrow">本周容量</div><div class="field"><label>本周可承诺专注时长（小时）</label><input id="capacity" type="number" min="1" max="100" value="'+state.settings.capacity+'"></div><button class="btn-secondary" onclick="saveSettings()">更新容量</button></section>\n\n <section class="setting-card"><div class="eyebrow">数据</div><p>可导出完整备份，换手机前请先保存 JSON 文件。</p><button class="btn-secondary" onclick="exportMenu()">导出与备份</button></section>'}

/* ════════════════════════════════════════════
   计时器全屏浮层
   ════════════════════════════════════════════ */
function timerClock(ms){var totalSec=Math.floor(Math.max(0,+ms||0)/1000),h=String(Math.floor(totalSec/3600)).padStart(2,'0'),m=String(Math.floor(totalSec/60)%60).padStart(2,'0'),s=String(totalSec%60).padStart(2,'0');return h+':'+m+':'+s}
function openTimerOverlay(taskId){var t=state.tasks.find(function(x){return x.id===taskId});if(!t)return;document.getElementById('timer-overlay')?.remove();var paused=state.timer?.paused;document.body.insertAdjacentHTML('beforeend','\n<div class="timer-overlay" id="timer-overlay">\n <button class="timer-close" onclick="closeTimerOverlay()">✕</button>\n <div class="timer-label" id="timer-label">'+(paused?'已暂停':'正在专注')+'</div>\n <div class="timer-task">'+esc(t.title)+'</div>\n <div class="timer-ring">'+ringSvg(0,200,6,'ring-fill')+'<div class="timer-display" id="timer-display">'+timerClock(taskActualMs(taskId))+'</div></div>\n <div class="timer-actions"><button class="btn-secondary" id="timer-toggle" onclick="'+(paused?'resumeTimer()':'pauseTimer()')+'">'+(paused?'▶ 继续':'⏸ 暂停')+'</button><button class="btn-primary" onclick="finishTask(\''+taskId+'\')">✓ 结束</button></div>\n</div>');cancelAnimationFrame(_timerRAF);_timerRAF=requestAnimationFrame(timerOverlayTick)}
function closeTimerOverlay(){cancelAnimationFrame(_timerRAF);document.getElementById('timer-overlay')?.remove();render()}
function timerOverlayTick(){if(!state.timer)return;var totalMs=taskActualMs(state.timer.taskId),el=document.getElementById('timer-display');if(el)el.textContent=timerClock(totalMs);var task=state.tasks.find(function(x){return x.id===state.timer.taskId}),totalEst=(+task?.estimate||60)*60000,pct=Math.min(1,totalMs/totalEst),ring=document.querySelector('#timer-overlay .ring-fill');if(ring){var r=(200-6)/2,c=2*Math.PI*r;ring.setAttribute('stroke-dashoffset',c*(1-pct))}_timerRAF=requestAnimationFrame(timerOverlayTick)}

/* ════════════════════════════════════════════
   滑动操作
   ════════════════════════════════════════════ */
function swipeStart(e,taskId){var item=document.getElementById('task-item-'+taskId);if(!item)return; _swipeState={taskId:taskId,item:item,startX:e.touches?e.touches[0].clientX:e.clientX,startY:e.touches?e.touches[0].clientY:e.clientY,offset:0}}
function swipeMove(e){if(!_swipeState)return;var clientX=e.touches?e.touches[0].clientX:e.clientX,clientY=e.touches?e.touches[0].clientY:e.clientY,dx=clientX-_swipeState.startX,dy=clientY-_swipeState.startY;if(Math.abs(dy)>Math.abs(dx))return; e.preventDefault();var offset=Math.min(0,Math.max(-144,dx));_swipeState.offset=offset;_swipeState.item.style.transform='translateX('+offset+'px)'}
function swipeEnd(){if(!_swipeState)return;var offset=_swipeState.offset; if(offset<-100)_swipeState.item.style.transform='translateX(-144px)';else _swipeState.item.style.transform='translateX(0)'; _swipeState=null}
function bindSwipes(){document.querySelectorAll('.task-row-wrap').forEach(function(wrap){var item=wrap.querySelector('.task-item');if(!item)return;var taskId=wrap.dataset.taskId;item.addEventListener('touchstart',function(e){swipeStart(e,taskId)},{passive:false});item.addEventListener('touchmove',swipeMove,{passive:false});item.addEventListener('touchend',swipeEnd)})}

/* ════════════════════════════════════════════
   渲染
   ════════════════════════════════════════════ */
function render(){var pages={today:pageToday,week:pageWeek,reports:pageReports,settings:pageSettings}; $('#app').innerHTML=pages[view]()+(view==='settings'?'':dockHtml())+navHtml();if(view==='week')bindSwipes();if(state.timer&&view==='today')tickInline()}
function dockHtml(){return '<form class="input-dock" onsubmit="submitCapture(event)"><input id="capture-input" autocomplete="off" placeholder="告诉秘书…" value="'+esc(draftText)+'"><button class="send" aria-label="发送">↑</button></form>'}
function navHtml(){var tabs=[{view:'today',label:'今天',icon:'🏠'},{view:'week',label:'本周',icon:'📅'},{view:'reports',label:'周报',icon:'📊'},{view:'settings',label:'设置',icon:'⚙️'}]; return '<nav class="nav">'+tabs.map(function(t){return '\n <button class="'+(view===t.view?'active':'')+'" onclick="go(\''+t.view+'\')"><span class="nav-icon">'+t.icon+'</span>'+t.label+'</button>'}).join('')+'</nav>'}
function go(v){view=v;render()} function settings(){go('settings')}

/* 内联计时器刷新 */
function tickInline(){if(!state.timer)return;var el=$('#timer-text');if(!el||view!=='today')return;el.textContent=timerClock(taskActualMs(state.timer.taskId));setTimeout(function(){tickInline()},500)}

/* ════════════════════════════════════════════
   输入解析
   ════════════════════════════════════════════ */
async function submitCapture(e){e.preventDefault();var input=$('#capture-input');draftText=input.value.trim();if(!draftText){toast('先告诉秘书一件事');return}try{await parseInput(draftText)}catch(error){close();toast('发送失败，请检查网络后重试');console.error('秘书输入处理失败',error)}}
async function parseInput(text){open('<h2>秘书正在整理</h2><p>正在判断任务、项目、依赖、本周容量与建议日期。</p><div class="notice">'+esc(text)+'</div>');var items=[],source='AI';try{items=state.settings.apiKey?await aiParse(text):heuristic(text);if(!state.settings.apiKey)source='本地规则'}catch(e){items=heuristic(text);source='本地规则';toast('AI 暂不可用，已使用本地规则')}items=prepareSchedule(items);showDraft(items,source)}
function heuristic(text){return text.split(/[，,、；;\n]/).map(function(part){return part.trim()}).filter(function(part){return part.length>1}).map(function(part){var life=/姐姐|朋友|老公|家里|被单|被套|大扫除|家庭财务|吃饭|聊天/.test(part),later=/下周|以后|暂缓|先录入|没办法完成/.test(part),clean=part.replace(/这周|需要|完成|安排|先录入|下周|估计没办法完成/g,' ').trim();return {title:clean,type:life?'life':'work',status:later?'later':'committed',project:'',estimate:life?30:60,kind:life&&/姐姐|朋友|老公|聊天|吃饭/.test(part)?'relation':life?'home':'other',dependsOn:[],priority:3,reason:later?'用户表达为下周或以后':'用户表达为本周'}})}
async function aiParse(text){var context={today:isoDate(),weekStart:currentWeekStart(),nextWeekStart:nextWeekStart(),remainingCapacityMinutes:Math.round(remaining()),rules:['没有观察区','周六不安排工作','日期由秘书建议','明确依赖必须严格遵守','生活不占工作专注容量'],existing:activeTasks().map(function(t){return {title:t.title,project:t.project,status:label(t.status),estimate:t.estimate,remaining:Math.round(taskPendingMinutes(t)),plannedDate:t.plannedDate}})},prompt='请解析用户输入并提出可确认的排程。每个事项字段：title,type(work|life),status(committed|later),project,estimate(分钟整数),kind(relation|home|other),dependsOn(前置事项标题数组),priority(1最高到5最低),plannedDate(YYYY-MM-DD),reason。不要拆成细步骤。用户输入：'+text+'\n上下文：'+JSON.stringify(context),r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.apiKey},body:JSON.stringify({model:'deepseek-chat',temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:'你是直接、现实的中文个人秘书。只输出 {"items":[...]}。本周超容量也不要自行编造观察区；保留用户本周意图，容量冲突由界面要求用户确认取舍。依赖顺序优先于日期。'},{role:'user',content:prompt}]})});if(!r.ok)throw Error('API');var data=await r.json(),parsed=JSON.parse(data.choices[0].message.content);return Array.isArray(parsed.items)?parsed.items:[]}
function nextSchedulableDate(date){var d=date||isoDate();while(new Date(d+'T12:00:00').getDay()===6)d=addDays(d,1);return d}
function prepareSchedule(items){var dayCounts={},lastDate=nextSchedulableDate(isoDate()),prepared=(items||[]).filter(function(x){return x&&String(x.title||'').trim()}).map(function(x){var item={...x,title:String(x.title).trim(),type:x.type==='life'?'life':'work',status:x.status==='later'||x.status==='next_week'?'later':'committed',estimate:Math.max(5,+x.estimate||60),dependsOn:Array.isArray(x.dependsOn)?x.dependsOn:[],priority:Math.min(5,Math.max(1,+x.priority||3))};if(item.status==='later'){item.plannedDate=nextSchedulableDate(nextWeekStart());return item}var proposed=/^\d{4}-\d{2}-\d{2}$/.test(item.plannedDate||'')?item.plannedDate:lastDate;if(proposed<isoDate())proposed=isoDate();proposed=nextSchedulableDate(proposed);while((dayCounts[proposed]||0)>=3)proposed=nextSchedulableDate(addDays(proposed,1));item.plannedDate=proposed;dayCounts[proposed]=(dayCounts[proposed]||0)+1;lastDate=proposed;return item}),byTitle={};prepared.forEach(function(x){byTitle[x.title]=x});prepared.forEach(function(x){(x.dependsOn||[]).forEach(function(name){var dep=byTitle[name]||state.tasks.find(function(t){return t.title===name});if(dep&&dep.plannedDate&&x.status==='committed'&&x.plannedDate<=dep.plannedDate)x.plannedDate=nextSchedulableDate(addDays(dep.plannedDate,1))})});return prepared}
function draftPayload(items){return encodeURIComponent(JSON.stringify(items))}
function readDraftEstimates(items){items.forEach(function(x,i){x.estimate=+document.querySelector('#est-'+i)?.value||x.estimate||60});return items}
function showDraft(items,source){var newWork=items.filter(function(x){return x.type==='work'&&x.status==='committed'}).reduce(function(n,x){return n+(+x.estimate||0)},0),overBy=Math.max(0,newWork-remaining()),replacement=activeTasks().filter(function(t){return !['active','paused','blocked'].includes(t.status)}).sort(function(a,b){return (b.priority||3)-(a.priority||3)||taskPendingMinutes(b)-taskPendingMinutes(a)})[0],body=items.map(function(x,i){var dep=x.dependsOn?.length?' · 依赖 '+esc(x.dependsOn.join('、')):'';return '\n <div class="task-draft"><div class="draft-title">'+esc(x.title)+'</div><div class="draft-meta">'+(x.type==='life'?'生活安排':'工作')+' · '+label(x.status)+(x.project?' · 建议归入 '+esc(x.project):'')+' · '+esc(x.plannedDate||'待安排')+dep+' · 预估 <input id="est-'+i+'" type="number" min="5" value="'+(x.estimate||60)+'"> 分钟</div><div class="draft-reason">'+esc(x.reason||'按当前顺序安排')+'</div></div>'}).join(''),payload=draftPayload(items),decision=overBy>0?'<div class="notice warn">不能把这些事项全部塞进本周：预计超出 '+hours(overBy)+'。'+(replacement?'要插入它，建议把「'+esc(replacement.title)+'」顺延到下周。':'建议把新事项放到下周，或明确开启例外冲刺。')+'</div>'+(replacement?'<button class="btn-primary" onclick="replaceAndConfirm(\''+payload+'\',\''+replacement.id+'\')">顺延「'+esc(replacement.title)+'」并录入</button>':'')+'<button class="btn-secondary" style="width:100%" onclick="moveNewToNextWeek(\''+payload+'\')">新工作全部放到下周</button><button class="btn-secondary" style="width:100%" onclick="confirmDraft(\''+payload+'\',true)">明确开启例外冲刺</button>':'<button class="btn-primary" onclick="confirmDraft(\''+payload+'\',false)">确认这份排程</button>';close();open('<h2>秘书建议这样安排</h2><p>'+esc(source)+' 已结合日期、容量和依赖给出建议；你确认后才生效。</p>'+body+decision+'<button class="btn-text" onclick="close()">返回修改</button>')}
function label(s){return ({committed:'本周承诺',later:'下周',blocked:'受阻',done:'已完成',active:'进行中',paused:'已暂停'}[s]||s)}
function decodeDraft(payload){return JSON.parse(decodeURIComponent(payload))}
function confirmDraft(payload,sprint){var items=readDraftEstimates(decodeDraft(payload)),newWork=items.filter(function(x){return x.type==='work'&&x.status==='committed'}).reduce(function(n,x){return n+(+x.estimate||0)},0);if(!sprint&&newWork>remaining()){showDraft(items,'容量复核');toast('修改后的估时超过本周容量，请先取舍');return}var created=[],titleMap={};state.tasks.forEach(function(t){titleMap[t.title]=t.id});items.filter(function(x){return x.type==='work'}).forEach(function(x){var task={id:id(),title:x.title,project:x.project||'',estimate:x.estimate,remaining:0,status:x.status,priority:x.priority||3,createdAt:new Date().toISOString(),weekStart:x.status==='later'?nextWeekStart():currentWeekStart(),plannedDate:x.plannedDate||isoDate(),dependsOn:[],blockedReason:''};created.push({task:task,names:x.dependsOn||[]});titleMap[task.title]=task.id;state.tasks.push(task)});created.forEach(function(entry){var missing=[];entry.task.dependsOn=entry.names.map(function(name){if(titleMap[name])return titleMap[name];missing.push(name);return null}).filter(Boolean);if(missing.length){entry.task.status='blocked';entry.task.blockedReason='等待 '+missing.join('、')}});items.filter(function(x){return x.type==='life'}).forEach(function(x){state.life.push({id:id(),title:x.title,kind:x.kind||'home',estimate:x.estimate,status:'planned',when:x.plannedDate||'本周找合适时间',plannedDate:x.plannedDate||isoDate(),weekStart:x.status==='later'?nextWeekStart():currentWeekStart()})});if(sprint&&!state.specialWeeks.includes(currentWeekStart()))state.specialWeeks.push(currentWeekStart());draftText='';close();save();toast(sprint?'已按例外冲刺录入，本周会单独标记':'已按建议排程录入')}
function replaceAndConfirm(payload,taskId){var old=state.tasks.find(function(t){return t.id===taskId});if(old){old.status='later';old.weekStart=nextWeekStart();old.plannedDate=nextSchedulableDate(nextWeekStart())}confirmDraft(payload,false)}
function moveNewToNextWeek(payload){var items=decodeDraft(payload).map(function(x){return x.type==='work'?{...x,status:'later',plannedDate:nextSchedulableDate(nextWeekStart())}:x});confirmDraft(draftPayload(items),false)}

/* ════════════════════════════════════════════
   计时器操作
   ════════════════════════════════════════════ */
function recordActiveSegment(){if(!state.timer||state.timer.paused||!state.timer.startedAt)return;var endedAt=new Date().toISOString(),durationMs=Math.max(0,new Date(endedAt)-new Date(state.timer.startedAt));state.sessions.push({id:id(),taskId:state.timer.taskId,startedAt:state.timer.startedAt,endedAt:endedAt,durationMs:durationMs,weekStart:weekStartOf(state.timer.startedAt)})}
function startTimer(taskId){if(state.timer&&state.timer.taskId!==taskId){toast('当前还有一件暂停或进行中的工作，请先结束它');return}var t=state.tasks.find(function(x){return x.id===taskId});if(!t)return;if(!dependencyReady(t)){toast('前置事项还没完成，暂时不能开始');return}if(!state.timer)state.timer={taskId:taskId,startedAt:new Date().toISOString(),paused:false};else if(state.timer.paused){state.timer.startedAt=new Date().toISOString();state.timer.paused=false}t.status='active';persist();render();openTimerOverlay(taskId)}
function pauseTimer(){if(!state.timer||state.timer.paused)return;recordActiveSegment();state.timer.startedAt=null;state.timer.paused=true;var t=state.tasks.find(function(x){return x.id===state.timer.taskId});if(t)t.status='paused';persist();render();openTimerOverlay(state.timer.taskId);toast('已暂停，累计投入 '+durationText(taskActualMs(state.timer.taskId)))}
function resumeTimer(){if(!state.timer||!state.timer.paused)return;state.timer.startedAt=new Date().toISOString();state.timer.paused=false;var t=state.tasks.find(function(x){return x.id===state.timer.taskId});if(t)t.status='active';persist();render();openTimerOverlay(state.timer.taskId)}

/* ════════════════════════════════════════════
   任务操作
   ════════════════════════════════════════════ */
function finishTask(taskId){if(state.timer?.taskId===taskId){recordActiveSegment();state.timer=null;persist();cancelAnimationFrame(_timerRAF);document.getElementById('timer-overlay')?.remove()}var t=state.tasks.find(function(x){return x.id===taskId});if(!t)return;open('<h2>这件事完成了吗？</h2><p>未完成也不是失败。告诉秘书还需多久。</p><div class="notice">'+esc(t.title)+' · 已投入 '+durationText(taskActualMs(taskId))+'</div><div class="row" style="margin-top:16px"><button class="btn-secondary" onclick="markRemaining(\''+taskId+'\')">还没完成</button><button class="btn-primary" onclick="markDone(\''+taskId+'\')">已完成</button></div>')}
function markDone(taskId){var t=state.tasks.find(function(x){return x.id===taskId});t.status='done';t.completedAt=new Date().toISOString();close();save();toast('完成已记录 ✓')}
function markRemaining(taskId){var t=state.tasks.find(function(x){return x.id===taskId});close();open('<h2>还需要多久？</h2><p>校准预估，不是自我批评。</p><div class="field"><label>预计剩余分钟</label><input id="remain" type="number" min="5" value="'+(t.remaining||t.estimate||60)+'"></div><button class="btn-primary" onclick="saveRemaining(\''+taskId+'\')">保存并重排</button>')}
function saveRemaining(taskId){var t=state.tasks.find(function(x){return x.id===taskId});t.remaining=+$('#remain').value||0;t.status='committed';close();save();toast(remaining()<0?'剩余工作已更新，本周已超容量，需要重排':'剩余工作已纳入本周')}
function lifeDone(i){var x=state.life.find(function(x){return x.id===i});x.status='done';save();toast('已记录。生活不是 KPI。')}
function taskMenu(i){var t=state.tasks.find(function(x){return x.id===i});open('<h2>'+esc(t.title)+'</h2><p>'+(t.project?'项目：'+esc(t.project):'尚未归属项目')+'</p><button class="btn-secondary" onclick="blockTask(\''+i+'\')">标记受阻</button><button class="btn-secondary danger" onclick="removeTask(\''+i+'\')">删除此项</button>')}
function blockTask(i){var t=state.tasks.find(function(x){return x.id===i});t.status='blocked';close();save();toast('已标记受阻，不再占用今日目标。')}
function removeTask(i){state.tasks=state.tasks.filter(function(x){return x.id!==i});close();save();toast('已移除')}
function planWeek(){var rem=remaining();open('<h2>本周容量检查</h2><p>秘书不会默默把新事塞进你的一周。</p><div class="notice '+(rem<0?'warn':'')+'">'+(rem>=0?'还可承诺 '+hours(rem)+'。':'本周已超容量 '+hours(-rem)+'。需要顺延、降级，或明确开启例外冲刺。')+'</div><p>周日 20:00-23:30 是默认规划窗口。周六不安排工作承诺。</p><button class="btn-primary" onclick="close()">我知道了</button>')}

/* ════════════════════════════════════════════
   导出
   ════════════════════════════════════════════ */
function download(name,type,data){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportMenu(){open('<h2>导出与备份</h2><p>导出后可换手机恢复。请妥善保管，JSON 包含本地设置。</p><button class="btn-primary" onclick="download(\'未尽-完整备份.json\',\'application/json\',JSON.stringify(state,null,2));close()">导出完整 JSON</button><button class="btn-secondary" style="margin-top:9px;width:100%" onclick="exportMd()">导出本周周报 Markdown</button><button class="btn-secondary" style="margin-top:9px;width:100%" onclick="exportCsv()">导出任务 CSV</button>')}
function exportMd(){var r=buildReport(),draft=state.reportDrafts?.[r.weekStart]||localReport(r),md='# 未尽 · 本周周报\n\n- 完成：'+r.done+'/'+r.total+'\n- 实际专注：'+durationText(r.actualMs)+'\n- 估时偏差：'+r.bias+'\n\n## 工作承诺\n'+r.tasks.map(function(t){return '- '+t.title+'：'+label(t.status)}).join('\n')+'\n\n## 生活安排（不计工作容量）\n'+r.life.map(function(x){return '- '+x.title+'：'+(x.status==='done'?'已完成':'本周安排')}).join('\n')+'\n\n## 秘书的判断\n'+draft.judgment+'\n\n## 下周建议\n'+draft.suggestions.map(function(x){return '- '+x}).join('\n')+'\n';download('未尽-本周周报.md','text/markdown;charset=utf-8',md);close()}
function exportCsv(){var rows=['任务,项目,状态,预计分钟,剩余分钟'];state.tasks.forEach(function(t){rows.push([t.title,t.project,label(t.status),t.estimate,t.remaining||''].map(function(v){return '"'+String(v).replace(/"/g,'""')+'"'}).join(','))});download('未尽-任务.csv','text/csv;charset=utf-8','﻿'+rows.join('\n'));close()}
function saveSettings(){state.settings.apiKey=$('#api-key').value.trim();state.settings.capacity=+$('#capacity').value||10;save();toast('设置已保存在本机')}

/* ════════════════════════════════════════════
   PWA
   ════════════════════════════════════════════ */
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();var result=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;toast(result.outcome==='accepted'?'正在安装未尽':'已取消安装');return}open('<h2>安装未尽</h2><p>请用 Chrome 打开本页，点击右上角菜单，选择"安装应用"或"安装未尽"。</p><button class="btn-primary" onclick="close()">我知道了</button>')}
window.addEventListener('beforeinstallprompt',function(event){event.preventDefault();deferredInstallPrompt=event;render()});window.addEventListener('appinstalled',function(){deferredInstallPrompt=null;toast('未尽已安装到桌面')});

/* ════════════════════════════════════════════
   启动
   ════════════════════════════════════════════ */
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=5');
render();
